// ETL-POC on Azure Container Apps.
//
// Deploy with infra/deploy.sh (or deploy.ps1), not by hand, because this
// template is applied twice and the order matters:
//
//   pass 1  deployWorkloads = false
//           Network, registry, storage, Postgres, Log Analytics and the
//           Container Apps environment. No apps and no jobs.
//   ...     Build and push both images. Regenerate the SFTP local-user
//           password and put it in Key Vault.
//   pass 2  deployWorkloads = true
//           The three apps and the two jobs.
//
// The split is not tidiness. A container app revision that cannot pull its
// image fails, and on pass 1 the images do not exist yet -- the registry was
// created by the same deployment. The Key Vault reference on the ingest job
// has the same problem: it is resolved when the revision starts, so the
// secret has to be there first.

targetScope = 'resourceGroup'

@description('Short prefix for every resource name. Lowercase letters, digits and hyphens.')
@minLength(3)
@maxLength(12)
param namePrefix string = 'etl-poc'

@description('Location for all resources.')
param location string = resourceGroup().location

@description('Tags applied to every resource.')
param tags object = {
  project: 'etl-poc'
  managedBy: 'bicep'
}

@description('Deploy the container apps and jobs. False on the first pass, before any image exists in the registry.')
param deployWorkloads bool = false

@description('Image tag for both images. deploy.sh uses the source commit, so a deployment names exactly what it is running.')
param imageTag string = 'latest'

@description('Deploy the SFTP landing zone, the lake container and the CDC source server. These replace the local atmoz/sftp, MinIO and postgres-source containers, and they cost real money -- SFTP bills hourly whenever it is enabled.')
param deployDemoSources bool = true

@description('Key Vault URI of the SFTP password secret. Empty on the first pass; deploy.sh supplies it on the second.')
param sftpPasswordSecretUri string = ''

@description('Administrator password for the CDC demo server. Generated by deploy.sh; ignored when deployDemoSources is false.')
@secure()
param cdcAdminPassword string = ''

@description('Give the Container Apps environment an internal load balancer only. The Dagster UI then has no public address.')
param internalOnly bool = false

@description('Allow registry access from outside the VNet. Needed to push images from a developer machine or a hosted CI runner.')
param registryAllowPublicNetworkAccess bool = true

@description('Allow storage and Key Vault access from outside the VNet. Needed to seed the sample data and write the SFTP secret.')
param storageAllowPublicNetworkAccess bool = true

@description('Email address for alerts. Empty creates the alert rules with no notification target.')
param alertEmail string = ''

@description('Seconds a run worker or ingest execution may run before Container Apps kills it. Keep it above ACA_INGEST_TIMEOUT_SECONDS so Dagster reports the timeout first, with a message that explains it.')
param replicaTimeoutSeconds int = 3600

// A VNet-integrated Flexible Server is addressed as <server>.<this zone>, so
// the zone name is part of every connection string in the deployment. It must
// end in .private.postgres.database.azure.com; Azure rejects anything else.
var postgresDnsZoneName = '${replace(namePrefix, '-', '')}.private.postgres.database.azure.com'

// Job names are computed, not read back from the job resources. That is what
// breaks the cycle: the code location needs to know the ingest job's name, and
// the ingest job needs to exist in the same environment as the code location.
var runJobName = 'caj-${namePrefix}-run'
var ingestJobName = 'caj-${namePrefix}-ingest'

var sftpFolderPath = '/sftp/retail'

// ---------------------------------------------------------------------------
module network 'modules/network.bicep' = {
  name: 'network'
  params: {
    namePrefix: namePrefix
    location: location
    tags: tags
    postgresDnsZoneName: postgresDnsZoneName
  }
}

module registry 'modules/registry.bicep' = {
  name: 'registry'
  params: {
    namePrefix: namePrefix
    location: location
    tags: tags
    privateEndpointSubnetId: network.outputs.privateEndpointSubnetId
    acrDnsZoneId: network.outputs.acrDnsZoneId
    allowPublicNetworkAccess: registryAllowPublicNetworkAccess
  }
}

module storage 'modules/storage.bicep' = {
  name: 'storage'
  params: {
    namePrefix: namePrefix
    location: location
    tags: tags
    privateEndpointSubnetId: network.outputs.privateEndpointSubnetId
    blobDnsZoneId: network.outputs.blobDnsZoneId
    dfsDnsZoneId: network.outputs.dfsDnsZoneId
    deploySftp: deployDemoSources
    allowPublicNetworkAccess: storageAllowPublicNetworkAccess
  }
}

module monitoring 'modules/monitoring.bicep' = {
  name: 'monitoring'
  params: {
    namePrefix: namePrefix
    location: location
    tags: tags
    alertEmail: alertEmail
    // The daemon alert scopes itself to an app that does not exist yet on the
    // first pass, so the rules wait for the workloads.
    deployAlerts: deployWorkloads
  }
}

// Identity comes after the registry, the storage account and the vault,
// because it grants itself roles on all three. A system-assigned identity
// could not: its role assignments would have to exist before the app that
// owns it, which is a cycle with no way out.
module identity 'modules/identity.bicep' = {
  name: 'identity'
  params: {
    namePrefix: namePrefix
    location: location
    tags: tags
    registryName: registry.outputs.registryName
    storageAccountName: storage.outputs.storageAccountName
    keyVaultName: storage.outputs.keyVaultName
  }
}

module postgres 'modules/postgres.bicep' = {
  name: 'postgres'
  params: {
    namePrefix: namePrefix
    location: location
    tags: tags
    delegatedSubnetId: network.outputs.postgresSubnetId
    privateDnsZoneId: network.outputs.postgresDnsZoneId
    adminPrincipalId: identity.outputs.principalId
    adminPrincipalName: identity.outputs.identityName
    deployCdcSource: deployDemoSources
    cdcAdminPassword: cdcAdminPassword
  }
}

module acaEnvironment 'modules/aca-environment.bicep' = {
  name: 'aca-environment'
  params: {
    namePrefix: namePrefix
    location: location
    tags: tags
    infrastructureSubnetId: network.outputs.acaSubnetId
    logAnalyticsWorkspaceId: monitoring.outputs.workspaceId
    internalOnly: internalOnly
  }
}

// ---------------------------------------------------------------------------
// Pass 2 only.
// ---------------------------------------------------------------------------
var orchestratorImage = '${registry.outputs.loginServer}/etl-poc-orchestrator:${imageTag}'
var ingestImage = '${registry.outputs.loginServer}/etl-poc-ingest:${imageTag}'

module apps 'modules/aca-apps.bicep' = if (deployWorkloads) {
  name: 'aca-apps'
  params: {
    namePrefix: namePrefix
    location: location
    tags: tags
    environmentId: acaEnvironment.outputs.environmentId
    registryLoginServer: registry.outputs.loginServer
    orchestratorImage: orchestratorImage
    identityId: identity.outputs.identityId
    identityClientId: identity.outputs.clientId
    postgresUser: identity.outputs.identityName
    postgresHost: postgres.outputs.warehouseFqdn
    dagsterDatabase: postgres.outputs.dagsterDatabaseName
    retailDatabase: postgres.outputs.retailDatabaseName
    storageAccountName: storage.outputs.storageAccountName
    blobEndpoint: storage.outputs.blobEndpoint
    runJobName: runJobName
    ingestJobName: ingestJobName
    sftpHost: storage.outputs.sftpHost
    sftpUserName: storage.outputs.sftpUserName
    sftpFolderPath: sftpFolderPath
  }
}

module jobs 'modules/aca-jobs.bicep' = if (deployWorkloads) {
  name: 'aca-jobs'
  params: {
    location: location
    tags: tags
    environmentId: acaEnvironment.outputs.environmentId
    registryLoginServer: registry.outputs.loginServer
    orchestratorImage: orchestratorImage
    ingestImage: ingestImage
    replicaTimeoutSeconds: replicaTimeoutSeconds
    identityId: identity.outputs.identityId
    identityClientId: identity.outputs.clientId
    postgresUser: identity.outputs.identityName
    postgresHost: postgres.outputs.warehouseFqdn
    dagsterDatabase: postgres.outputs.dagsterDatabaseName
    retailDatabase: postgres.outputs.retailDatabaseName
    storageAccountName: storage.outputs.storageAccountName
    blobEndpoint: storage.outputs.blobEndpoint
    runJobName: runJobName
    ingestJobName: ingestJobName
    sftpHost: storage.outputs.sftpHost
    sftpUserName: storage.outputs.sftpUserName
    sftpFolderPath: sftpFolderPath
    sftpPasswordSecretUri: sftpPasswordSecretUri
  }
}

// ---------------------------------------------------------------------------
output registryLoginServer string = registry.outputs.loginServer
output registryName string = registry.outputs.registryName
output storageAccountName string = storage.outputs.storageAccountName
output keyVaultName string = storage.outputs.keyVaultName
output keyVaultUri string = storage.outputs.keyVaultUri
output sftpLocalUserName string = storage.outputs.sftpLocalUserName
output sftpHost string = storage.outputs.sftpHost
output sftpUserName string = storage.outputs.sftpUserName
output postgresFqdn string = postgres.outputs.warehouseFqdn
output postgresUser string = identity.outputs.identityName
output cdcFqdn string = postgres.outputs.cdcFqdn
output containerAppsEnvironment string = acaEnvironment.outputs.environmentName
output runJobName string = runJobName
output ingestJobName string = ingestJobName
// apps! rather than apps: the module is conditional, so its type is
// nullable, and the ternary alone does not tell the compiler the access is
// guarded.
output dagsterUrl string = deployWorkloads ? 'https://${apps!.outputs.webserverFqdn}' : ''
output codeServerHost string = deployWorkloads ? apps!.outputs.codeServerHost : ''
