"""Synthetic data assets.

The second ingestion path, kept in its own asset group and off the schedule. It
shares the cache, the Pipes plumbing and the subprocess pattern with the SFTP
route but needs no server, no files and no network -- which is what makes it the
useful one for generating volume on demand during model testing.

See docs/local-ingestion-options.md for the alternatives this stands in for.
"""

# Dagster resolves the `context`, `config` and resource parameter annotations on
# this function at runtime to build the op definition, so this module must not
# use `from __future__ import annotations` -- PEP 563 would turn them into
# strings that Dagster cannot resolve.
from dagster import (
    AssetExecutionContext,
    AssetSpec,
    Config,
    PipesSubprocessClient,
    multi_asset,
)

from ingest.streams import FAKER_SCHEMA, FAKER_STREAM_NAMES
from pipeline.config import INGEST_PYTHON, ingest_env

GROUP_NAME = "synthetic_ingest"


class FakerConfig(Config):
    """Run-time knobs, editable in the Dagster UI before launching."""

    count: int = 10_000
    seed: int = 42


FAKER_ASSET_SPECS = [
    AssetSpec(
        key=[FAKER_SCHEMA, name],
        group_name=GROUP_NAME,
        description=f"Synthetic {name} generated by source-faker.",
        kinds={"airbyte", "postgres"},
        metadata={"destination_table": f"{FAKER_SCHEMA}.{name}"},
    )
    for name in FAKER_STREAM_NAMES
]


@multi_asset(
    specs=FAKER_ASSET_SPECS,
)
def synthetic_ingest(
    context: AssetExecutionContext,
    config: FakerConfig,
    pipes_subprocess_client: PipesSubprocessClient,
):
    """Generate synthetic records and load them into their own schema."""
    context.log.info(f"generating {config.count} records with seed {config.seed}")

    return pipes_subprocess_client.run(
        command=[str(INGEST_PYTHON), "-m", "ingest.run_faker_sync"],
        context=context,
        extras={"count": config.count, "seed": config.seed},
        env=ingest_env(),
    ).get_results()
